genesis_id = ""
system = "Blockstack"
dependencies = [""]
icon = "blockstack"

[token]
name = " token"
symbol = ""

[consensus]
consensus_type = ""
consensus_name = ""

[descriptions]
state = "Project"
system_type = "cryptoasset"
headline = "Blockstack is a new internet for decentralized apps. "

[crowdsales]
start_date = "2017-11-01T18:00:00"
end_date = "2017-11-20T11:59:00"
end_date_plan = "2017-11-20T11:59:00"
genesis_address = [""]
funding_terms = "https://blockstack.com/distribution.pdf"
funding_url = "https://blockstack.com/"
tokens_sold = ""
tokens_issued = ""
btc_raised = ""
cap_limit = [""]
raised = [""]

[specs]
supply = 0

[[links]]
type = "website"
name = "blockstack.org"
url = "https://blockstack.org/"
tags = ["Main"]

[[links]]
type = "paper"
name = "Blockstack Whitepaper"
url = "https://blockstack.com/tokenpaper.pdf"
tags = ["Main", "Science"]

[[links]]
type = "github"
name = "Blockstack Github"
url = "https://github.com/blockstack"
icon = "github.png"
tags = ["Main", "Code"]

[[links]]
type = "blog"
name = " Blog"
url = ""
icon = "medium.png"
tags = ["Main", "News"]

[[links]]
type = "forum"
name = "Bitcointalk"
url = ""
icon = "bitcointalk.png"
tags = ["News"]

[[links]]
type = "twitter"
name = "Twitter"
url = ""
icon = "twitter.png"
tags = ["News"]

[[links]]
type = "custom"
name = " Telegram"
url = ""
icon = "telegram.png"
tags = ["News"]

[[links]]
type = "reddit"
name = "Reddit"
url = ""
icon = "reddit.png"
tags = ["News"]

[[links]]
type = "custom"
name = "Facebook"
url = ""
icon = "facebook.png"
tags = ["News"]
