genesis_id = ""
system = "Game Machine"
dependencies = ["Ethereum"]
icon = "gamemachine"

[token]
name = " token"
symbol = ""

[consensus]
consensus_type = "ERC20 Token"
consensus_name = "Ethereum"

[descriptions]
state = "Project"
system_type = "cryptoasset"
headline = "The global open ecosystem for game industry based on blockchain"

[crowdsales]
start_date = "2017-11-01T00:01:00"
end_date = "2017-12-31T23:29:00"
end_date_plan = "2017-12-31T23:29:00"
genesis_address = [""]
funding_terms = ""
funding_url = ""
tokens_sold = ""
tokens_issued = ""
btc_raised = ""
cap_limit = [""]
raised = [""]

[specs]
supply = 0

[[links]]
type = "website"
name = "gamemachine.io"
url = "https://gamemachine.io/en"
tags = ["Main"]

[[links]]
type = "paper"
name = "Game Machine Whitepaper"
url = "https://gamemachine.io/en/token-sale/whitepaper"
tags = ["Main", "Science"]

[[links]]
type = "github"
name = "Game Machine Github"
url = ""
icon = "github.png"
tags = ["Main", "Code"]

[[links]]
type = "blog"
name = " Blog"
url = ""
icon = "medium.png"
tags = ["Main", "News"]

[[links]]
type = "forum"
name = "Bitcointalk"
url = ""
icon = "bitcointalk.png"
tags = ["News"]

[[links]]
type = "twitter"
name = "Twitter"
url = ""
icon = "twitter.png"
tags = ["News"]

[[links]]
type = "custom"
name = " Telegram"
url = ""
icon = "telegram.png"
tags = ["News"]

[[links]]
type = "reddit"
name = "Reddit"
url = ""
icon = "reddit.png"
tags = ["News"]

[[links]]
type = "custom"
name = "Facebook"
url = ""
icon = "facebook.png"
tags = ["News"]
