genesis_id = ""
system = "MediBloc"
dependencies = [""]
icon = "medibloc"

[token]
name = " token"
symbol = ""

[consensus]
consensus_type = ""
consensus_name = ""

[descriptions]
state = "Project"
system_type = "cryptoasset"
headline = "The largest Healthcare Blockchain."

[crowdsales]
start_date = "2017-11-20T02:00:00"
end_date = "2017-11-26T03:00:00"
end_date_plan = "2017-11-26T03:00:00"
genesis_address = [""]
funding_terms = "https://medium.com/medibloc/pre-sale-participation-guideline-70b459ba5453"
funding_url = "https://medibloc.org"
tokens_sold = ""
tokens_issued = ""
btc_raised = ""
cap_limit = [""]
raised = [""]

[specs]
supply = 0

[[links]]
type = "website"
name = "medibloc.org"
url = "https://medibloc.org"
tags = ["Main"]

[[links]]
type = "paper"
name = "MediBloc Whitepaper"
url = "https://medibloc.org/whitepaper/medibloc_whitepaper_en.pdf"
tags = ["Main", "Science"]

[[links]]
type = "github"
name = "MediBloc Github"
url = "https://github.com/Medibloc"
icon = "github.png"
tags = ["Main", "Code"]

[[links]]
type = "blog"
name = " Blog"
url = ""
icon = "medium.png"
tags = ["Main", "News"]

[[links]]
type = "forum"
name = "Bitcointalk"
url = ""
icon = "bitcointalk.png"
tags = ["News"]

[[links]]
type = "twitter"
name = "Twitter"
url = ""
icon = "twitter.png"
tags = ["News"]

[[links]]
type = "custom"
name = " Telegram"
url = ""
icon = "telegram.png"
tags = ["News"]

[[links]]
type = "reddit"
name = "Reddit"
url = ""
icon = "reddit.png"
tags = ["News"]

[[links]]
type = "custom"
name = "Facebook"
url = ""
icon = "facebook.png"
tags = ["News"]
