genesis_id = ""
system = "MindSports IO "
dependencies = ["Ethereum"]
icon = "mindsportsio"

[token]
name = " token"
symbol = ""

[consensus]
consensus_type = "ERC20 Token"
consensus_name = "Ethereum"

[descriptions]
state = "Project"
system_type = "cryptoasset"
headline = "Social Gaming Network to Host, Play and Vote Intellectual Games"

[crowdsales]
start_date = "2017-11-09T14:00:00"
end_date = "2017-12-08T02:00:00"
end_date_plan = "2017-12-08T02:00:00"
genesis_address = [""]
funding_terms = "https://www.mindsports.io/mindsports_whitepaper.pdf"
funding_url = "https://www.mindsports.io "
tokens_sold = ""
tokens_issued = ""
btc_raised = ""
cap_limit = [""]
raised = [""]

[specs]
supply = 0

[[links]]
type = "website"
name = "www.mindsports.io"
url = "https://www.mindsports.io"
tags = ["Main"]

[[links]]
type = "paper"
name = "MindSports IO  Whitepaper"
url = "https://www.mindsports.io/mindsports_whitepaper.pdf"
tags = ["Main", "Science"]

[[links]]
type = "github"
name = "MindSports IO  Github"
url = "https://github.com/mindsports"
icon = "github.png"
tags = ["Main", "Code"]

[[links]]
type = "blog"
name = " Blog"
url = ""
icon = "medium.png"
tags = ["Main", "News"]

[[links]]
type = "forum"
name = "Bitcointalk"
url = ""
icon = "bitcointalk.png"
tags = ["News"]

[[links]]
type = "twitter"
name = "Twitter"
url = ""
icon = "twitter.png"
tags = ["News"]

[[links]]
type = "custom"
name = " Telegram"
url = ""
icon = "telegram.png"
tags = ["News"]

[[links]]
type = "reddit"
name = "Reddit"
url = ""
icon = "reddit.png"
tags = ["News"]

[[links]]
type = "custom"
name = "Facebook"
url = ""
icon = "facebook.png"
tags = ["News"]
