genesis_id = ""
system = "NAU"
dependencies = ["Ethereum"]
icon = "nau"

[token]
name = " token"
symbol = ""

[consensus]
consensus_type = "ERC20 Token"
consensus_name = "Ethereum"

[descriptions]
state = "Project"
system_type = "cryptoasset"
headline = "NAU is a platform that connects retailers with customers"

[crowdsales]
start_date = "2017-11-01T12:00:00"
end_date = "2017-12-17T12:00:00"
end_date_plan = "2017-12-17T12:00:00"
genesis_address = [""]
funding_terms = "https://tokensale.nau.io/pdf/NAU_WhitePaper.pdf"
funding_url = "https://tokensale.nau.io/"
tokens_sold = ""
tokens_issued = ""
btc_raised = ""
cap_limit = [""]
raised = [""]

[specs]
supply = 0

[[links]]
type = "website"
name = "tokensale.nau.io"
url = "https://tokensale.nau.io/"
tags = ["Main"]

[[links]]
type = "paper"
name = "NAU Whitepaper"
url = "https://tokensale.nau.io/pdf/NAU_WhitePaper.pdf"
tags = ["Main", "Science"]

[[links]]
type = "github"
name = "NAU Github"
url = "https://github.com/nau-dev?tab=repositories"
icon = "github.png"
tags = ["Main", "Code"]

[[links]]
type = "blog"
name = " Blog"
url = ""
icon = "medium.png"
tags = ["Main", "News"]

[[links]]
type = "forum"
name = "Bitcointalk"
url = ""
icon = "bitcointalk.png"
tags = ["News"]

[[links]]
type = "twitter"
name = "Twitter"
url = ""
icon = "twitter.png"
tags = ["News"]

[[links]]
type = "custom"
name = " Telegram"
url = ""
icon = "telegram.png"
tags = ["News"]

[[links]]
type = "reddit"
name = "Reddit"
url = ""
icon = "reddit.png"
tags = ["News"]

[[links]]
type = "custom"
name = "Facebook"
url = ""
icon = "facebook.png"
tags = ["News"]
