genesis_id = ""
system = "Pareto Network"
dependencies = [""]
icon = "paretonetwork"

[token]
name = " token"
symbol = ""

[consensus]
consensus_type = ""
consensus_name = ""

[descriptions]
state = "Project"
system_type = "cryptoasset"
headline = "Current reputable & actionable content for digital marketplace "

[crowdsales]
start_date = "2017-12-01T00:00:00"
end_date = "2017-12-31T00:00:00"
end_date_plan = "2017-12-31T00:00:00"
genesis_address = [""]
funding_terms = "https://pareto.network/download/Pareto-Technical-White-Paper.pdf"
funding_url = "https://www.pareto.network/"
tokens_sold = ""
tokens_issued = ""
btc_raised = ""
cap_limit = [""]
raised = [""]

[specs]
supply = 0

[[links]]
type = "website"
name = "www.pareto.network"
url = "https://www.pareto.network/"
tags = ["Main"]

[[links]]
type = "paper"
name = "Pareto Network Whitepaper"
url = "https://pareto.network/download/Pareto-Technical-White-Paper.pdf"
tags = ["Main", "Science"]

[[links]]
type = "github"
name = "Pareto Network Github"
url = ""
icon = "github.png"
tags = ["Main", "Code"]

[[links]]
type = "blog"
name = " Blog"
url = ""
icon = "medium.png"
tags = ["Main", "News"]

[[links]]
type = "forum"
name = "Bitcointalk"
url = ""
icon = "bitcointalk.png"
tags = ["News"]

[[links]]
type = "twitter"
name = "Twitter"
url = ""
icon = "twitter.png"
tags = ["News"]

[[links]]
type = "custom"
name = " Telegram"
url = ""
icon = "telegram.png"
tags = ["News"]

[[links]]
type = "reddit"
name = "Reddit"
url = ""
icon = "reddit.png"
tags = ["News"]

[[links]]
type = "custom"
name = "Facebook"
url = ""
icon = "facebook.png"
tags = ["News"]
