
genesis_id = ""
system = "RightMesh"
dependencies = ["Ethereum"]
icon = "rightmesh"

[token]
name = "rightmesh token"
symbol = "MESH"

[consensus]
consensus_type = "ERC20 Token"
consensus_name = "Ethereum"

[descriptions]
state = "Project"
system_type = "cryptoasset"
headline = "Connect the Right Way"

[crowdsales]
start_date = "2018-02-13T00:00:00"
end_date = "2018-02-27T23:59:00"
end_date_plan = "2018-02-27T23:59:00"
genesis_address = [""]
funding_terms = "https://www.rightmesh.io/whitepaper/"
funding_url = "https://www.rightmesh.io/ "
tokens_sold = ""
tokens_issued = ""
btc_raised = ""
cap_limit = [""]
raised = [""]

[[links]]
type = "website"
name = "www.rightmesh.io"
url = "https://www.rightmesh.io/ "
tags = ["Main"]

[[links]]
type = "paper"
name = "RightMesh Whitepaper"
url = "https://www.rightmesh.io/whitepaper/"
tags = ["Main", "Science"]

[[links]]
type = "github"
name = "RightMesh Github"
url = "https://github.com/RightMesh"
icon = "github.png"
tags = ["Main", "Code"]

[[links]]
type = "twitter"
name = "Twitter"
url = "https://twitter.com/Right_Mesh"
icon = "twitter.png"
tags = ["News"]

[[links]]
type = "custom"
name = "Facebook"
url = "https://www.facebook.com/TheRightMesh/"
icon = "facebook.png"
tags = ["News"]

[[links]]
type = "custom"
name = "YouTube"
url = "https://www.youtube.com/channel/UCa-am0tFMgJbDP2_yYFhfRA"
icon = "youtube.png"
tags = ["News"]
