
genesis_id = ""
system = "StopTheFakes"
dependencies = ["Ethereum"]
icon = "stopthefakes"

[token]
name = "stf token"
symbol = "STF"

[consensus]
consensus_type = "ERC20 Token"
consensus_name = "Ethereum"

[descriptions]
state = "Project"
system_type = "cryptoasset"
headline = "Anti-Counterfeit & Copyright Infringement Blockchain Service"

[crowdsales]
start_date = "2017-11-21T09:00:00"
end_date = "2017-12-20T09:00:00"
end_date_plan = "2017-12-20T09:00:00"
genesis_address = [""]
funding_terms = "https://stopthefakes.io/docs/WP_En.pdf"
funding_url = "https://stopthefakes.io"
tokens_sold = ""
tokens_issued = ""
btc_raised = ""
cap_limit = [""]
raised = [""]

[specs]
supply = 29000000 

[[links]]
type = "website"
name = "stopthefakes.io"
url = "https://stopthefakes.io"
tags = ["Main"]

[[links]]
type = "paper"
name = "StopTheFakes Whitepaper"
url = "https://stopthefakes.io/docs/WP_En.pdf"
tags = ["Main", "Science"]

[[links]]
type = "github"
name = "StopTheFakes Github"
url = "https://github.com/StopTheFakes/crowdsale-token/blob/master/crowdsale-token.sol"
icon = "github.png"
tags = ["Main", "Code"]

[[links]]
type = "blog"
name = "StopTheFakes Blog"
url = "https://medium.com/@stopthefakes"
icon = "medium.png"
tags = ["Main", "News"]

[[links]]
type = "forum"
name = "Bitcointalk"
url = "https://bitcointalk.org/index.php?topic=2279900.0"
icon = "bitcointalk.png"
tags = ["News"]

[[links]]
type = "twitter"
name = "Twitter"
url = "https://twitter.com/StopTheFakes_io"
icon = "twitter.png"
tags = ["News"]

[[links]]
type = "custom"
name = "StopTheFakes Telegram"
url = "https://t.me/stopthefakes"
icon = "telegram.png"
tags = ["News"]

[[links]]
type = "reddit"
name = "Reddit"
url = "https://www.reddit.com/r/stopthefakes/"
icon = "reddit.png"
tags = ["News"]

[[links]]
type = "custom"
name = "Facebook"
url = "https://www.facebook.com/Stopthefakes-137209146891736/"
icon = "facebook.png"
tags = ["News"]
