[description]
project_name = ""
headline = ""
logo = ""
state = 3 # 0 - Project, 1 - Pre-public, 2 - Public
asset_type = "" # cryptocurrency, cryptoasset

[[legal_entity]]
name = ""
residence = ""
purpose = ""
shareholders_list = ""
registration_date = ""
venture_capital_funding = ""

[ico]

  [ico.common_info]
  is_ico = true
  current_ico_phase = 0 # 0 - pre-sale, 1 - ICO phase 1, 2 - ICO phase 2 etc

    [ico.common_info.registration]
    start_date = ""
    end_date = ""
    website = ""
    terms = ""

    [[ico.common_info.token]]
    name = ""
    symbol = ""
    dependency = ""
    consensus = ""
    token_type = ""
    inflation_rate = ""
    circulation_terms = ""
    governance_rights_project = ""
    governance_rights_org = ""

    [ico.common_info.token_distribution]
    total_supply = ""

      [[ico.common_info.token_distribution.shares]]
      description = ""
      share = 0

      [[ico.common_info.token_distribution.shares]]
      description = ""
      share = 0

    [[ico.common_info.use_of_proceeds]]
    description = ""
    share = 0

  [[ico.phases]]
  phase_num = 0 # 0 - pre-sale, 1 - ICO phase 1, 2 - ICO phase 2 etc

    [ico.phases.terms]
    sales_agreement = ""
    sales_url = ""
    issued_tokens = 0
    sold_tokens = 0
    share_of_sold = 0 # Filled by cyberanalytics team
    vesting = ""
    cap_limit = 0
    crowdsale_adresses = ""
    token_distribution_date = ""

    [ico.phases.dates]
    start_date = ""
    end_date = ""
    duration = 0 # Filled by cyberanalytics team

    [ico.phases.raised_funds]
    eth = 0 # Filled by cyberanalytics team

    [ico.phases.prices]
    token_initial_price = 0

    [[ico.phases.contract]]
    contract_type = "" # Filled by cyberanalytics team
    contract_adress = "" # Filled by cyberanalytics team

[product]

  [product.info]
  same_blockchain = false
  sources_availability = true # Filled by cyberanalytics team
  product_status = 2 # 
  app_type = ""
  app_url = ""

    [[product.info.token]]
    name = ""
    symbol = ""
    dependency = ""
    consensus = ""

    [[product.info.milestouns]]
    number = 0
    name = ""
    start_date = ""
    end_date = ""
    current_status = ""

[[links]]
type = ""
name = ""
url = ""
tags = ["tag"]
