
genesis_id = ""
system = "wys Token"
dependencies = ["Ethereum"]
icon = "wystoken"

[token]
name = "wys token"
symbol = "WYS"

[consensus]
consensus_type = "ERC20 Token"
consensus_name = "Ethereum"

[descriptions]
state = "Project"
system_type = "cryptoasset"
headline = "Visual mobile shopping experience with token for e-commerce"

[crowdsales]
start_date = "2017-11-01T14:00:00"
end_date = "2017-12-01T14:00:00"
end_date_plan = "2017-12-01T14:00:00"
genesis_address = [""]
funding_terms = "https://www.wystoken.org/media/wysker-whitepaper.pdf"
funding_url = "https://www.wystoken.org"
tokens_sold = ""
tokens_issued = ""
btc_raised = ""
cap_limit = [""]
raised = [""]

[specs]
supply = 0

[[links]]
type = "website"
name = "wystoken.org"
url = "https://www.wystoken.org"
tags = ["Main"]

[[links]]
type = "paper"
name = "wys Token Whitepaper"
url = "https://www.wystoken.org/media/wysker-whitepaper.pdf"
tags = ["Main", "Science"]

[[links]]
type = "github"
name = "wys Token Github"
url = "https://github.com/wysker"
icon = "github.png"
tags = ["Main", "Code"]

[[links]]
type = "blog"
name = "wys Token Blog"
url = "https://medium.com/wysker"
icon = "medium.png"
tags = ["Main", "News"]

[[links]]
type = "twitter"
name = "Twitter"
url = "https://twitter.com/wysker_"
icon = "twitter.png"
tags = ["News"]

[[links]]
type = "slack"
name = "wys Token Slack"
url = "https://goo.gl/forms/VxK4S4K3XZc7P69X2"
icon = "slack.png"
tags = ["News"]

[[links]]
type = "custom"
name = "Facebook"
url = "https://www.facebook.com/wysker/"
icon = "facebook.png"
tags = ["News"]

[[links]]
type = "custom"
name = "YouTube"
url = "https://www.youtube.com/watch?v=xg_OEr2UqKY"
icon = "youtube.png"
tags = ["News"]
